[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# Remap "@chainlink/contracts/" to brownie
remappings = ["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"]
# Allows foundry to run commands on your machine
ffi = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
